# Generated by Django 6.1.1 on 2026-10-09 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Короткий опис')),
                ('area', models.CharField(choices=[('ui_ux', 'UI/UX'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'База даних'), ('devops', 'DevOps'), ('qa', 'QA'), ('other', 'Інше')], max_length=20, verbose_name='Де баг')),
                ('severity', models.CharField(choices=[('low', 'Низька'), ('medium', 'Середня'), ('high', 'Висока'), ('critical', 'Критична')], default='medium', max_length=10, verbose_name='Важливість')),
                ('status', models.CharField(choices=[('new', 'Новий'), ('in_progress', 'У роботі'), ('fixed', 'Виправлено'), ('closed', 'Закрито'), ('wontfix', 'Не буде виправлено')], default='new', max_length=12, verbose_name='Статус')),
                ('steps', models.TextField(verbose_name='Кроки відтворення')),
                ('expected', models.TextField(blank=True, verbose_name='Очікуваний результат')),
                ('actual', models.TextField(blank=True, verbose_name='Фактичний результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bugs', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.bug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
